---
title: "Task 12"
output: 
  html_document:
    keep_md: TRUE
    code_folding: 'hide'
---

**Chance Lister**
  
```{r}

library(tidyverse)
library(readxl)
library(readr)
library(downloader)
```
# Import
```{r}



mdata <- tempfile()

mdata

tempdir()
download("https://raw.githubusercontent.com/WJC-Data-Science/DTS350/master/messy_data.xlsx",
         mdata, mode = "wb")

m_data <- read_xlsx(mdata)

view(m_data)
```

# Tidy

```{r}

m_data1 <- subset(m_data, select = -c(3,4,6,7,9,10,12,13,15,16))

m_data2 <- m_data1 %>%
  pivot_longer(c('...5','...8','...11','...14','...17'), names_to = 'Class', values_to = 'Grades')

view(m_data2)


m_df <- na.omit(m_data2)

view(m_df)
```

#Visualization/Data

```{r}

m_vis <- ggplot(data = m_df) +
  geom_bar(mapping = aes(x = Grades, fill = Grades))

m_vis

head(m_df, 20)

ggsave(
  filename = "Task12_graph1.png",
  plot = last_plot(),
  width = 15,
  units = c("in"),
  dpi = 300
)
```

This visualization shows the total amount of grades in all the classes overall. The classes seem to be going well for the students as we see most of the grades above a B, there is a concerning amount of students that have an F in the classes.
