---
title: "Task 13"
output: 
  html_document:
    keep_md: TRUE
    code_folding: hide
---

**Chance Lister**

```{r}
library(readr)
library(haven)
library(readxl)
library(downloader)
library(tidyverse)
```
# Reading in Data
```{r}
df_rds  <- read_rds(url("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.RDS"))
df_dta  <- read_dta("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.dta")
df_cvs  <- read_csv("https://raw.githubusercontent.com/WJC-Data-Science/DTS350/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.csv")

sav <- tempfile()
download("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.sav", sav, mode = "wb")

df_sav <- read_sav(sav)

xlsx <- tempfile()
download("https://github.com/WJC-Data-Science/DTS350/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.xlsx",xlsx, mode = "wb")

df_xlsx <- read_xlsx(xlsx)
```
# Checking if Equal
```{r}
all_equal(df_dta, df_sav, convert = TRUE)
all_equal(df_dta, df_xlsx, convert = TRUE)
all_equal(df_dta, df_rds, convert = TRUE)
all_equal(df_rds, df_sav, convert = TRUE)
all_equal(df_rds, df_xlsx, convert = TRUE)
all_equal(df_xlsx, df_sav, convert = TRUE)
```
# Grouping/Mean
```{r}
df_dta2 <- df_dta %>% 
  separate(contest_period, into = c("Month_to_Month", "Year_End"), sep = -4)

df_dta3 <- df_dta %>% 
  separate(contest_period, into = c("Month_to_Month", "Year_End"), sep = -4) %>%
  group_by(Year_End, variable) %>%
  summarise( mean = mean(value))

view(df_dta2)
```
# Graphic
```{r}
graphic_1 <- ggplot(data = df_dta2) +
  geom_boxplot(mapping = aes(x = Year_End, y = value)) +
  labs(x = "Year End", 
       y = "Price", 
       color = "Stocks", 
       title = "Preformance of Pro Stock Selections") +
  theme_minimal()

graphic_1

graphic_2 <- ggplot(data = df_dta3) +
  geom_line(mapping = aes(x = Year_End, y = mean, color = variable, group = variable)) +
  labs(x = "Year End", 
       y = "Price", 
       color = "Stocks", 
       title = "Mean Price of Stocks") +
  theme_minimal()

graphic_2

graphic_3 <- ggplot(data = df_dta2) + 
  geom_jitter(mapping = aes(x = Year_End, y = value, color = variable))+
  labs(x = "Year End",
       y = "Price",
       color = "Stock",
       title = "Prices of Sticks over Years") +
  theme_minimal()

graphic_3

graphic_4 <- ggplot(data = df_dta3) +
  geom_line( mapping = aes(group = variable, x = Year_End , y = mean, color  = variable), size = 1.5)+
  geom_jitter( data = df_dta2, mapping = aes(x = Year_End, y = value, color = variable))+
  labs(x = "Year End",
       y = "Price",
       color = "Stock",
       title = "Prices and Mean Prices of Stocks")

graphic_4
```
# Tidying Data
```{r}
df_tidy <- df_dta2 %>%
  separate(`Month_to_Month`, into = c("month_begin","month_end"), sep = "-")

view(df_tidy)
```
# Saving Tidy Data
```{r}
saveRDS(df_tidy,"dft_tidy.rds")
```
# Six Month Returns Plots
```{r}
month_return <- ggplot(data = df_dta2) +
  geom_point(mapping = aes(x = Year_End, y = value, color = variable)) +
  labs(x = "Year End",
       y = "Price",
       color = "Stock",
       title = "Prices and Mean Prices of Stocks") +
  theme_minimal()

month_return
```
# Final Table
```{r}
df_dta4 <- df_tidy %>%
  mutate(month_end = replace(month_end, month_end == "Dec.", "December")) %>%
  mutate(month_end = replace(month_end, month_end == "Febuary", "February")) %>%
  select(-c(month_begin)) %>%
  filter(variable == "DJIA") %>%
  pivot_wider(names_from = Year_End, values_from = value) %>%
  select(-c(variable)) %>%
  mutate(month_end = replace(month_end, month_end == "January", 1)) %>%
  mutate(month_end = replace(month_end, month_end == "February", 2)) %>%
  mutate(month_end = replace(month_end, month_end == "March", 3)) %>%
  mutate(month_end = replace(month_end, month_end == "April", 4)) %>%
  mutate(month_end = replace(month_end, month_end == "May", 5)) %>%
  mutate(month_end = replace(month_end, month_end == "June", 6)) %>%
  mutate(month_end = replace(month_end, month_end == "July", 7)) %>%
  mutate(month_end = replace(month_end, month_end == "August", 8)) %>%
  mutate(month_end = replace(month_end, month_end == "September", 9)) %>%
  mutate(month_end = replace(month_end, month_end == "October", 10)) %>%
  mutate(month_end = replace(month_end, month_end == "November", 11)) %>%
  mutate(month_end = replace(month_end, month_end == "December", 12)) 

df_dta4$month_end <- as.integer(df_dta4$month_end)

df_dta4 <- df_dta4[order(df_dta4$month_end),]

df_dta4 <- df_dta4 %>%
  mutate(month_end = replace(month_end, month_end == 1,"January")) %>%
  mutate(month_end = replace(month_end, month_end == 2,"February")) %>%
  mutate(month_end = replace(month_end, month_end == 3,"March")) %>%
  mutate(month_end = replace(month_end, month_end == 4,"April")) %>%
  mutate(month_end = replace(month_end, month_end == 5,"May")) %>%
  mutate(month_end = replace(month_end, month_end == 6,"June")) %>%
  mutate(month_end = replace(month_end, month_end == 7,"July")) %>%
  mutate(month_end = replace(month_end, month_end == 8,"August")) %>%
  mutate(month_end = replace(month_end, month_end == 9,"September")) %>%
  mutate(month_end = replace(month_end, month_end == 10,"October")) %>%
  mutate(month_end = replace(month_end, month_end == 11,"November")) %>%
  mutate(month_end = replace(month_end, month_end == 12,"December"))

head(df_dta4, 12)
```